"""
PDF report generation using ReportLab.
"""

import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm


def generate_pdf_report(company_name: str, year: int, ratios: dict, score: float, prediction: str, explanation: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=20, spaceAfter=12)
    story.append(Paragraph("Financial Analysis Report", title_style))
    story.append(Paragraph(f"Company: {company_name} | Year: {year}", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))

    # Prediction badge
    color_map = {"Profitable": colors.green, "Moderate": colors.orange, "High Risk": colors.red}
    pred_color = color_map.get(prediction, colors.grey)
    pred_style = ParagraphStyle("pred", parent=styles["Heading2"], textColor=pred_color)
    story.append(Paragraph(f"Prediction: {prediction}  |  Score: {score}/100", pred_style))
    story.append(Paragraph(explanation, styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))

    # Ratios table
    story.append(Paragraph("Financial Ratios", styles["Heading2"]))
    ratio_labels = {
        "net_profit_margin": "Net Profit Margin (%)",
        "roa": "Return on Assets (%)",
        "roe": "Return on Equity (%)",
        "current_ratio": "Current Ratio",
        "quick_ratio": "Quick Ratio",
        "debt_to_equity": "Debt-to-Equity",
        "asset_turnover": "Asset Turnover",
        "operating_cf_positive": "Positive Operating Cash Flow",
    }
    table_data = [["Ratio", "Value"]]
    for key, label in ratio_labels.items():
        val = ratios.get(key)
        if isinstance(val, bool):
            val = "Yes" if val else "No"
        elif isinstance(val, float):
            val = f"{val:.2f}"
        table_data.append([label, str(val)])

    t = Table(table_data, colWidths=[10*cm, 5*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f4f8")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Generated by FinAnalyst Platform", styles["Italic"]))

    doc.build(story)
    return buffer.getvalue()
